resource_types:
- name: packer
  type: docker-image
  source:
    repository: jdub/packer-resource

resources:
- name: build-ami
  type: packer
  source:
    aws_access_key_id: {{aws_access_key}}
    aws_secret_access_key: {{aws_secret_access}}
    region: us-west-2

jobs:
- name: my-ami
  plan:
  - put: build-ami
    params:
      template: packer_nuxeo.json
      var_file: secrets.json
